name: buildzr-dev
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pytest
  - pyhumps
  - mypy
  - jsondiff
  - pytest-mypy
  - typing_extensions
  - pip
  - yq
  - mkdocs
  - mkdocs-material
  - datamodel-code-generator
  - jpype1>=1.4.0
  - ipykernel
  - pip:
      - -e ".[export-plantuml]"
      - pypinfo
      - mkdocstrings[python]
prefix: /opt/conda/envs/buildzr-dev
