name: buildzr-dev
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pytest
  - pyhumps
  - mypy
  - jsondiff
  - pytest-mypy
  - pip
  - yq
  - datamodel-code-generator
  - pip:
      - -e .
      - pypinfo
prefix: /opt/conda/envs/buildzr-dev
